# Generated by Django 2.0.6 on 2018-07-25 13:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeldingOpenbareRuimte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('hoofdcategorie', models.CharField(max_length=255)),
                ('subcategorie', models.CharField(max_length=255)),
                ('locatie_beschrijving', models.TextField(blank=True, help_text='Aanvullende omschrijving locatie')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'melding openbare ruimte',
                'verbose_name_plural': 'meldingen openbare ruimte',
            },
        ),
    ]
