# Generated by Django 2.0.6 on 2018-07-25 13:49

from django.db import migrations, models
import uuid
import zds_schema.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatuurlijkPersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('naam', models.CharField(max_length=200)),
                ('bsn', zds_schema.fields.BSNField(max_length=9)),
                ('telefoonnummer', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'natuurlijk persoon',
                'verbose_name_plural': 'natuurlijke personen',
            },
        ),
    ]
