# Generated by Django 2.0.6 on 2018-12-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inzageverzoek',
            options={'verbose_name': 'inzage verzoek', 'verbose_name_plural': 'inzage verzoeken'},
        ),
    ]
