# Generated by Django 2.0.6 on 2018-06-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straatnaam', models.CharField(help_text='De officiële straatnaam zoals door het bevoegd gemeentelijk orgaan is vastgesteld, zo nodig ingekort conform de specificaties van de NEN 5825.', max_length=50)),
                ('postcode', models.CharField(max_length=7)),
                ('woonplaatsnaam', models.CharField(max_length=80)),
                ('huisnummer', models.CharField(max_length=5)),
                ('huisletter', models.CharField(blank=True, max_length=1)),
                ('huisnummertoevoeging', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='VerblijfsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=50)),
                ('hoofdadres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datamodel.Adres')),
            ],
            options={
                'verbose_name': 'Verblijfsobject',
                'verbose_name_plural': 'Verblijfsobjecten',
            },
        ),
    ]
