# Generated by Django 2.0.6 on 2018-07-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_adres_verblijfsobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomeinData',
        ),
    ]
