# Generated by Django 2.0.6 on 2018-08-17 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_delete_domeindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NietNatuurlijkPersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('rsin', models.CharField(help_text='Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON', max_length=17)),
                ('statutaire_naam', models.TextField(blank=True, help_text='Naam van de niet-natuurlijke persoon zoals deze is vastgelegd in de statuten (rechtspersoon) of in de vennootschapsovereenkomst is overeengekomen (Vennootschap onder firma of Commanditaire vennootschap).', max_length=500)),
                ('datum_aanvang', models.DateField(help_text='De datum van aanvang van de NIET-NATUURLIJK PERSOON')),
                ('datum_beeindiging', models.DateField(blank=True, help_text='De datum van beëindiging van de NIET-NATUURLIJK PERSOON.', null=True)),
            ],
            options={
                'verbose_name': 'niet-natuurlijk persoon',
                'verbose_name_plural': 'niet-natuurlijke personen',
            },
        ),
    ]
